# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "pq-board"
BBFILE_PATTERN_pq-board = "^${LAYERDIR}/"
BBFILE_PRIORITY_pq-board = "6"

# bitbake -e | grep "^DISTRO_CODENAME="
LAYERDEPENDS_pq-board = "core"
LAYERSERIES_COMPAT_pq-board = "scarthgap"
