name: Build Yocto Image

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:
    inputs:
      trigger:
        description: "start manually"
        required: true
        default: "yes"
  #schedule:
  #  - cron: '0 2 * * 0'  # jeden Sonntag um 02:00 Uhr nachts  

jobs:
  build:
    runs-on: [self-hosted, pqbox-runner]
    env:
      ORGANISATION_NAME: "emblincram"
      CONTAINER_NAME: "devcon"
      LAYER_NAME: "meta-emblincram"

    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to GitHub Container Registry
        run: |
          echo "$GHCR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Prepare Workspace
        run: |
          # todo: set proper user
          # move cache and downloads 
          docker run --rm \
            -v ${{ runner.workspace }}/../:/mnt \
            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-clean:latest /bin/bash -i -c "
              mkdir -p /mnt/sstate-cache /mnt/downloads

              #mv /mnt/${{ github.event.repository.name }}/sstate-cache/* /mnt/sstate-cache/ || true
              #mv /mnt/${{ github.event.repository.name }}/downloads/* /mnt/downloads/ || true

              chmod -R a+rw /mnt/sstate-cache /mnt/downloads
            "

          # cleanup workspace
          docker run --rm \
            -v ${{ runner.workspace }}/:/mnt \
            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-clean:latest /bin/bash -i -c "
              rm -rf /mnt/*
              mkdir -p /mnt/${{ github.event.repository.name }} /mnt/logs /mnt/build
              chmod -R 777 /mnt
            "

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true

      - name: Run Yocto Build
        run: |
          cd ${{ github.workspace }}
          set -eo pipefail

          docker run --rm \
            -v ${{ github.workspace }}:/home/yocto \
            -v ${{ runner.workspace }}/../sstate-cache:/home/yocto/sstate-cache \
            -v ${{ runner.workspace }}/../downloads:/home/yocto/downloads \
            -v ${{ runner.workspace }}/logs:/home/yocto/logs \
            -w /home/yocto \
            --user "$(id -u):$(id -g)" \
            --env GITHUB_TOKEN=$GHCR_PAT \
            --env YOCTO_SSTATE_DIR=/home/yocto/sstate-cache \
            --env YOCTO_DL_DIR=/home/yocto/downloads \
            --env YOCTO_LOGS_DIR=/home/yocto/logs \
            ghcr.io/$ORGANISATION_NAME/$CONTAINER_NAME-min:latest /bin/bash -i -c "
              cd .scripts || { echo 'ERROR: Konnte nicht in .scripts wechseln'; exit 1; }
              chmod +x post-create-command.sh
              ./post-create-command.sh /home/yocto/ || { echo 'ERROR: Skript konnte nicht ausgeführt werden'; exit 1; }
              cd ..

              [ -f .scripts/activate-env.sh ] && cp .scripts/activate-env.sh . || echo 'Error: .scripts/activate-env.sh fehlt'
              chmod +x activate-env.sh

              . activate-env.sh || echo 'Error: activate-env.sh konnte nicht ausgeführt werden'

              TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
              bitbake core-image-full-cmdline 2>&1 | tee /home/yocto/logs/build-log_$TIMESTAMP.txt
            "
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: yocto-build-logs
          path: ${{ runner.workspace }}/logs/build-log_*.txt
          retention-days: 14
    
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yocto-image
          path: ${{ runner.workspace }}/build/deploy-ti/images/beagle-x15/core-image-full-cmdline-*.wic*
          retention-days: 14
